---
- name: Ensure Flathub remote is configured
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user
    state: present

- name: Install flatpak packages
  community.general.flatpak:
    name: "{{ item }}"
    method: user
    remote: flathub
    state: latest
  loop: "{{ flatpak_apps | default([]) }}"
