---
- name: Ensure Flathub remote is configured
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  when: ansible_facts["system"] == 'Linux'
  become: yes
  changed_when: false

- name: Install flatpak packages
  flatpak:
    name: "{{ item }}"
    state: present
    method: system
  loop: "{{ (chezmoi_data.packages.common.flatpak.linux | default([])) + (chezmoi_data.packages[profile].flatpak.linux | default([])) }}"
  when: ansible_facts["system"] == 'Linux'
  become: yes
  ignore_errors: yes
