---
- name: Ensure Flathub remote is configured
  command:
    argv:
      - sudo
      - -S
      - -p
      - ""
      - flatpak
      - remote-add
      - --if-not-exists
      - flathub
      - https://flathub.org/repo/flathub.flatpakrepo
  stdin: "{{ lookup('file', dotfiles_sudo_password_file) }}"
  no_log: true
  when:
    - ansible_facts["system"] == 'Linux'
    - not (dotfiles_ci | default(false))
  changed_when: false

- name: Install flatpak packages
  command:
    argv:
      - sudo
      - -S
      - -p
      - ""
      - flatpak
      - install
      - --system
      - --noninteractive
      - flathub
      - "{{ item }}"
  stdin: "{{ lookup('file', dotfiles_sudo_password_file) }}"
  no_log: true
  loop: "{{ (chezmoi_data.packages.common.flatpak.linux | default([])) + (chezmoi_data.packages[profile].flatpak.linux | default([])) }}"
  when:
    - ansible_facts["system"] == 'Linux'
    - not (dotfiles_ci | default(false))
  ignore_errors: yes
