#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
installer_files=()
for candidate in "$repo_root"/home/.chezmoiscripts/*.tmpl "$repo_root"/ansible/roles/features/mise/tasks/*.yml "$repo_root"/home/.chezmoidata/ai-clis.yaml; do
  [ -f "$candidate" ] && installer_files+=("$candidate")
done

failures=0
fail() {
  echo "FAIL: $*" >&2
  failures=$((failures + 1))
}

if [ "${#installer_files[@]}" -eq 0 ]; then
  echo "No upstream installer files found; nothing to check."
  exit 0
fi

if grep -nE 'raw\.githubusercontent\.com/[^/ ]+/[^/ ]+/v?[0-9]+\.[0-9]+' "${installer_files[@]}"; then
  fail "an installer URL above pins a version; use the upstream default branch so the installer itself stays current"
fi
if grep -nE 'expected_sha256|sha256sum -c|shasum -a 256 -c|[0-9a-f]{64}' "${installer_files[@]}"; then
  fail "an installer above is pinned by checksum; upstream changes would break the install instead of being picked up"
fi
if grep -nE 'MISE_VERSION=|MISE_VERSION:' "${installer_files[@]}"; then
  fail "an installer above pins the mise version; the mise.run installer resolves the current release itself"
fi

installer_urls="$(
  {
    grep -ohE 'curl -[A-Za-z]+ https://[^ "'"'"')|]+ \| (sh|bash)' "${installer_files[@]}" | sed -E 's/^curl -[A-Za-z]+ //; s/ \| (sh|bash)$//' || true
    grep -ohE 'https://[^ "'"'"')]+/install\.sh' "${installer_files[@]}" || true
  } 2>/dev/null | sort -u
)"
if [ -z "$installer_urls" ]; then
  echo "No upstream installer URLs found in ${installer_files[*]#"$repo_root"/}; nothing to download."
  [ "$failures" -eq 0 ] || exit 1
  exit 0
fi

if ! curl -fsSL --max-time 30 -o /dev/null https://raw.githubusercontent.com/ 2>/dev/null \
  && ! curl -fsSL --max-time 30 -o /dev/null https://github.com/ 2>/dev/null; then
  echo "No network access to GitHub; skipping the live upstream installer checks."
  [ "$failures" -eq 0 ] || exit 1
  exit 0
fi

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

for url in $installer_urls; do
  name="$(printf '%s' "$url" | sed -E 's|https://||; s|[^A-Za-z0-9]+|-|g')"
  if ! curl -fsSL --max-time 30 "$url" >"$tmpdir/$name.sh"; then
    fail "$url is not downloadable"
    continue
  fi
  case "$url" in
    https://mise.run)
      embedded="$(sed -nE 's/^.*MISE_VERSION:-v?([0-9]+\.[0-9]+\.[0-9]+).*$/\1/p' "$tmpdir/$name.sh" | head -n 1)"
      published="$(curl -fsSL --max-time 30 https://mise.jdx.dev/VERSION 2>/dev/null | tr -d '[:space:]' | sed -E 's/^v//')"
      if [ -z "$embedded" ]; then
        fail "$url no longer embeds the release it installs; review the upstream installer"
      elif [ -z "$published" ]; then
        echo "note: could not read https://mise.jdx.dev/VERSION; $url installs mise $embedded"
      elif [ "$embedded" != "$published" ]; then
        fail "$url installs mise $embedded but upstream publishes $published; the installer is no longer regenerated per release"
      else
        echo "ok: $url installs the current mise release ($embedded)"
      fi
      ;;
    *)
      if grep -Fq 'releases/latest' "$tmpdir/$name.sh"; then
        echo "ok: $url resolves the latest release at run time"
      elif grep -qE '^(VER|VERSION)="?v?[0-9]+\.[0-9]+\.[0-9]+"?$' "$tmpdir/$name.sh"; then
        echo "ok: $url is regenerated by the vendor per release ($(grep -oE '^(VER|VERSION)="?v?[0-9]+\.[0-9]+\.[0-9]+"?$' "$tmpdir/$name.sh" | head -n 1))"
      else
        fail "$url no longer resolves the latest release (expected a 'releases/latest' lookup or a vendor-embedded version); review the upstream installer"
      fi
      ;;
  esac
done

if [ "$failures" -ne 0 ]; then
  echo "$failures upstream installer check(s) failed" >&2
  exit 1
fi
echo "Upstream installer checks passed"
