---
- name: Set bash as default shell (Linux)
  ansible.builtin.shell: |
    set -euo pipefail

    if [ -n {{ dotfiles_sudo_password_file | quote }} ]; then
      sudo -S -p '' chsh -s /bin/bash {{ ansible_facts['user_id'] | quote }} < {{ dotfiles_sudo_password_file | quote }}
    else
      sudo -n chsh -s /bin/bash {{ ansible_facts['user_id'] | quote }}
    fi
  args:
    executable: /bin/bash
  ignore_errors: yes
  changed_when: false
