---
- name: Install system packages (Archlinux)
  ansible.builtin.shell: |
    set -euo pipefail

    if [ -n {{ dotfiles_sudo_password_file | quote }} ]; then
      sudo -S -p '' pacman -S --noconfirm --needed {{ system_packages | map('quote') | join(' ') }} < {{ dotfiles_sudo_password_file | quote }}
    else
      sudo -n pacman -S --noconfirm --needed {{ system_packages | map('quote') | join(' ') }}
    fi
  args:
    executable: /bin/bash
