---
- name: Merge package lists
  set_fact:
    system_packages: >-
      {{
        (
          (chezmoi_data.packages.common.system[dotfiles_platform.distro_key] | default([])) +
          (chezmoi_data.packages[profile].system[dotfiles_platform.distro_key] | default([]))
        )
        | reject('equalto', 'flatpak')
        | list
        if dotfiles_ci | default(false)
        else
        (
          (chezmoi_data.packages.common.system[dotfiles_platform.distro_key] | default([])) +
          (chezmoi_data.packages[profile].system[dotfiles_platform.distro_key] | default([]))
        )
      }}
    homebrew_brews: "{{ (chezmoi_data.packages.common.homebrew.brews | default([])) + (chezmoi_data.packages[profile].homebrew.brews | default([])) }}"
    homebrew_casks: >-
      {{
        []
        if dotfiles_ci | default(false)
        else
        (
          (chezmoi_data.packages.common.homebrew.casks | default([])) +
          (chezmoi_data.packages[profile].homebrew.casks | default([]))
        )
      }}

- name: Install Linux system packages
  include_tasks: "linux-{{ dotfiles_platform.distro_key }}.yml"
  when:
    - dotfiles_platform.system == 'Linux'
    - dotfiles_platform.distro_key != ''
    - system_packages | length > 0

- name: Install Homebrew packages
  include_tasks: macos.yml
  when:
    - dotfiles_platform.os_family == 'Darwin'

- name: Install JetBrains Toolbox helper
  include_tasks: linux-jetbrains-toolbox.yml
  when:
    - dotfiles_platform.system == 'Linux'
    - not (dotfiles_ci | default(false))
