---
- name: Run chezmoi apply
  command:
    argv:
      - chezmoi
      - apply
      - --source
      - "{{ chezmoi_dir }}"
      - --override-data
      - "{{ dotfiles_chezmoi_setup_data | default({}) | to_json }}"
      - --force
      - -v
  environment:
    PROFILE: "{{ profile }}"
  register: chezmoi_result
  changed_when: false
