---
- name: Enable Docker service (Linux)
  command:
    argv:
      - sudo
      - -S
      - -p
      - ""
      - systemctl
      - enable
      - --now
      - docker
  stdin: "{{ lookup('file', dotfiles_sudo_password_file) }}"
  no_log: true
  when: install_docker | default(false) and ansible_facts["system"] == 'Linux'
  ignore_errors: yes
